"""
Python web3.py interface for the TransactionContract smart contract.

Provides a clean, Pythonic API over the raw web3.py calls:
    - Fund wallets in the on-chain ledger
    - Submit, approve, and reject transactions
    - Query balances and transaction records
    - Fetch indexed on-chain events

Security:
    - All addresses are validated through web3's to_checksum_address before
      any contract call, preventing mixed-case address bugs.
    - No private keys are handled here; callers configure web3's account
      middleware (e.g. via web3.middleware.signing) separately.
    - ABI is loaded from Hardhat's compiled artifact, not hardcoded, so the
      interface always matches the deployed bytecode version.

Typical usage::

    from web3 import Web3
    from blockchain.contract import ContractInterface

    w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:7545"))

    # From deployment.json (written by scripts/deploy.js)
    ci = ContractInterface.from_deployment_file(w3)

    ci.fund_wallet("0xabc...", amount_ether=1.0, sender=w3.eth.accounts[0])
    tx_hash = ci.submit_transaction(
        sender=w3.eth.accounts[1],
        receiver=w3.eth.accounts[2],
        value_ether=0.5,
        fee_ether=0.001,
    )
    ci.approve_transaction(tx_hash, owner=w3.eth.accounts[0])
    record = ci.get_transaction(tx_hash)
"""

import json
from pathlib import Path
from typing import Any

from web3 import Web3

from wallet.config import configure_logging

logger = configure_logging(__name__)

# Path to the Hardhat compiled artifact (generated by `npx hardhat compile`)
_ABI_PATH: Path = (
    Path(__file__).resolve().parent.parent
    / "artifacts"
    / "contracts"
    / "TransactionContract.sol"
    / "TransactionContract.json"
)

# Default deployment info file (written by scripts/deploy.js)
_DEPLOYMENT_PATH: Path = (
    Path(__file__).resolve().parent.parent / "deployment.json"
)


def load_abi(artifact_path: Path | None = None) -> list[dict[str, Any]]:
    """Load the contract ABI from a Hardhat compiled artifact file.

    Args:
        artifact_path: Path to the JSON artifact.
            Defaults to ``artifacts/contracts/TransactionContract.sol/
            TransactionContract.json`` (Hardhat output).

    Returns:
        The ABI as a list of dicts.

    Raises:
        FileNotFoundError: If the artifact file does not exist.
            Run ``npx hardhat compile`` to generate it.
    """
    path = artifact_path or _ABI_PATH
    if not path.exists():
        raise FileNotFoundError(
            f"Contract artifact not found: {path}\n"
            "Run 'npx hardhat compile' to generate the ABI."
        )
    with path.open() as fh:
        artifact = json.load(fh)
    return artifact["abi"]  # type: ignore[no-any-return]


# Status enum — matches order in Solidity ``enum Status { Pending, Approved, Rejected }``
_STATUS_LABELS: tuple[str, ...] = ("Pending", "Approved", "Rejected")


class ContractInterface:
    """Python interface to the deployed TransactionContract.

    Args:
        web3:             Connected Web3 instance.
        contract_address: Checksummed Ethereum address of the deployed contract.
        abi:              Contract ABI.  If ``None``, loaded from the Hardhat
                          artifact at ``_ABI_PATH``.

    Raises:
        FileNotFoundError: If ``abi`` is None and the artifact file is missing.
    """

    def __init__(
        self,
        web3: Web3,
        contract_address: str,
        abi: list[dict[str, Any]] | None = None,
    ) -> None:
        self.w3 = web3
        self.address: str = Web3.to_checksum_address(contract_address)
        _abi = abi if abi is not None else load_abi()
        self.contract = self.w3.eth.contract(address=self.address, abi=_abi)
        logger.info("ContractInterface connected to %s", self.address)

    # ------------------------------------------------------------------
    # Factory
    # ------------------------------------------------------------------

    @classmethod
    def from_deployment_file(
        cls,
        web3: Web3,
        deployment_path: Path | str | None = None,
        abi: list[dict[str, Any]] | None = None,
    ) -> "ContractInterface":
        """Create a ContractInterface from a ``deployment.json`` file.

        ``deployment.json`` is written by ``scripts/deploy.js`` after a
        successful ``npx hardhat run`` deploy.

        Args:
            web3:            Connected Web3 instance.
            deployment_path: Path to the deployment JSON file.
                Defaults to ``deployment.json`` in the project root.
            abi:             Override ABI (useful in tests).

        Returns:
            A configured ``ContractInterface`` instance.

        Raises:
            FileNotFoundError: If ``deployment.json`` is not found.
        """
        path = Path(deployment_path) if deployment_path else _DEPLOYMENT_PATH
        if not path.exists():
            raise FileNotFoundError(
                f"Deployment file not found: {path}\n"
                "Run 'npx hardhat run scripts/deploy.js --network ganache' first."
            )
        with path.open() as fh:
            info = json.load(fh)
        address: str = info["address"]
        logger.info(
            "Loaded deployment from %s (network: %s, address: %s)",
            path,
            info.get("network"),
            address,
        )
        return cls(web3, address, abi)

    # ------------------------------------------------------------------
    # Wallet funding
    # ------------------------------------------------------------------

    def fund_wallet(
        self,
        wallet: str,
        amount_ether: float,
        sender: str,
    ) -> Any:
        """Credit a wallet's on-chain ledger balance by sending ETH.

        Args:
            wallet:       The Ethereum address to credit.
            amount_ether: Amount in Ether to deposit.
            sender:       Account that pays the ETH (must hold a balance).

        Returns:
            Web3 transaction receipt.
        """
        amount_wei = self.w3.to_wei(amount_ether, "ether")
        tx = self.contract.functions.fundWallet(
            Web3.to_checksum_address(wallet)
        ).transact({"from": sender, "value": amount_wei})
        receipt = self.w3.eth.wait_for_transaction_receipt(tx)
        logger.info(
            "Funded %s with %.6f ETH (tx: %s)",
            wallet,
            amount_ether,
            tx.hex(),
        )
        return receipt

    # ------------------------------------------------------------------
    # Transaction lifecycle
    # ------------------------------------------------------------------

    def submit_transaction(
        self,
        sender: str,
        receiver: str,
        value_ether: float,
        fee_ether: float,
    ) -> bytes:
        """Submit a transaction to the smart contract for owner approval.

        The contract reserves ``value + fee`` from the sender's ledger
        balance, creates a Pending record, and emits ``TransactionSubmitted``.

        Args:
            sender:       Sender's Ethereum address (must have funded balance).
            receiver:     Receiver's Ethereum address.
            value_ether:  Transfer value in Ether.
            fee_ether:    Transaction fee in Ether.

        Returns:
            The ``bytes32`` transaction hash assigned by the contract.

        Raises:
            RuntimeError: If the ``TransactionSubmitted`` event is not emitted.
        """
        value_wei = self.w3.to_wei(value_ether, "ether")
        fee_wei = self.w3.to_wei(fee_ether, "ether")

        tx = self.contract.functions.submitTransaction(
            Web3.to_checksum_address(receiver),
            value_wei,
            fee_wei,
        ).transact({"from": sender})
        receipt = self.w3.eth.wait_for_transaction_receipt(tx)

        # Extract the returned txHash from the emitted event
        logs = self.contract.events.TransactionSubmitted().process_receipt(receipt)
        if not logs:
            raise RuntimeError(
                "TransactionSubmitted event not emitted — deployment may be wrong."
            )
        contract_tx_hash: bytes = logs[0]["args"]["txHash"]
        logger.info(
            "Transaction submitted — contract hash: %s",
            contract_tx_hash.hex(),
        )
        return contract_tx_hash

    def approve_transaction(self, contract_tx_hash: bytes, owner: str) -> Any:
        """Approve a Pending transaction (contract owner only).

        Credits the receiver's ledger balance with the transaction value.
        The fee remains in the contract (simulated miner reward).

        Args:
            contract_tx_hash: The ``bytes32`` hash from :meth:`submit_transaction`.
            owner:            The contract owner account address.

        Returns:
            Web3 transaction receipt.
        """
        tx = self.contract.functions.approveTransaction(contract_tx_hash).transact(
            {"from": owner}
        )
        receipt = self.w3.eth.wait_for_transaction_receipt(tx)
        logger.info("Transaction approved: %s", contract_tx_hash.hex())
        return receipt

    def reject_transaction(
        self,
        contract_tx_hash: bytes,
        owner: str,
        reason: str = "Policy violation",
    ) -> Any:
        """Reject a Pending transaction and refund the sender (owner only).

        Args:
            contract_tx_hash: The ``bytes32`` hash from :meth:`submit_transaction`.
            owner:            The contract owner account address.
            reason:           Human-readable rejection reason stored on-chain.

        Returns:
            Web3 transaction receipt.
        """
        tx = self.contract.functions.rejectTransaction(
            contract_tx_hash, reason
        ).transact({"from": owner})
        receipt = self.w3.eth.wait_for_transaction_receipt(tx)
        logger.info(
            "Transaction rejected: %s — reason: %s",
            contract_tx_hash.hex(),
            reason,
        )
        return receipt

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_transaction(self, contract_tx_hash: bytes) -> dict[str, Any]:
        """Fetch a transaction record from the contract.

        Args:
            contract_tx_hash: The ``bytes32`` transaction hash.

        Returns:
            Dict with keys:
                ``sender``, ``receiver``, ``value_ether``, ``fee_ether``,
                ``status`` (``"Pending"``, ``"Approved"``, or ``"Rejected"``),
                ``timestamp``, ``reject_reason``.
        """
        record = self.contract.functions.getTransaction(contract_tx_hash).call()
        return {
            "sender": record[0],
            "receiver": record[1],
            "value_ether": float(self.w3.from_wei(record[2], "ether")),
            "fee_ether": float(self.w3.from_wei(record[3], "ether")),
            "status": _STATUS_LABELS[record[4]],
            "timestamp": record[5],
            "reject_reason": record[6],
        }

    def get_balance(self, wallet: str) -> float:
        """Return the ledger balance in Ether for a wallet.

        Args:
            wallet: The Ethereum address to query.

        Returns:
            Balance in Ether as a float.
        """
        wei: int = self.contract.functions.getBalance(
            Web3.to_checksum_address(wallet)
        ).call()
        return float(self.w3.from_wei(wei, "ether"))

    def get_tx_count(self) -> int:
        """Return the total number of submitted transactions.

        Returns:
            Integer count of all transactions ever submitted to this contract.
        """
        return int(self.contract.functions.getTxCount().call())

    def get_tx_hash_at(self, index: int) -> bytes:
        """Return the transaction hash at a given submission index.

        Args:
            index: Zero-based position in submission order.

        Returns:
            ``bytes32`` transaction hash.
        """
        return bytes(self.contract.functions.getTxHashAt(index).call())

    # ------------------------------------------------------------------
    # Events
    # ------------------------------------------------------------------

    def get_submitted_events(self, from_block: int = 0) -> list[dict[str, Any]]:
        """Fetch all ``TransactionSubmitted`` events from the chain.

        Args:
            from_block: Starting block number. Use 0 for all history.

        Returns:
            List of event argument dicts.
        """
        events = self.contract.events.TransactionSubmitted.get_logs(
            fromBlock=from_block
        )
        return [dict(e["args"]) for e in events]

    def get_approved_events(self, from_block: int = 0) -> list[dict[str, Any]]:
        """Fetch all ``TransactionApproved`` events from the chain.

        Args:
            from_block: Starting block number. Use 0 for all history.

        Returns:
            List of event argument dicts.
        """
        events = self.contract.events.TransactionApproved.get_logs(
            fromBlock=from_block
        )
        return [dict(e["args"]) for e in events]

    def get_rejected_events(self, from_block: int = 0) -> list[dict[str, Any]]:
        """Fetch all ``TransactionRejected`` events from the chain.

        Args:
            from_block: Starting block number. Use 0 for all history.

        Returns:
            List of event argument dicts.
        """
        events = self.contract.events.TransactionRejected.get_logs(
            fromBlock=from_block
        )
        return [dict(e["args"]) for e in events]
